package ai.openonion.oochat.ui.theme

import android.app.Activity
import android.os.Build
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.dynamicDarkColorScheme
import androidx.compose.material3.dynamicLightColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.SideEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.platform.LocalInspectionMode
import androidx.compose.ui.platform.LocalView
import androidx.compose.ui.unit.Density
import androidx.core.view.WindowCompat
import ai.openonion.oochat.data.local.DataStoreAppSettings
import ai.openonion.oochat.domain.model.ThemeMode
import ai.openonion.oochat.ui.common.FontSizeOption
import kotlinx.coroutines.flow.flowOf

// Colors generated by Material Theme Builder live in Color.kt.
private val LightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

private val DarkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)

/**
 * The user's "Font size" setting as a scale factor, read straight from
 * DataStore (the same trick MainActivity uses for [ThemeMode]) so the theme
 * doesn't need it prop-drilled in from an Activity or a ViewModel.
 *
 * Previews and any context without a usable DataStore fall back to 1f.
 */
@Composable
private fun userFontScale(): Float {
    if (LocalInspectionMode.current) return 1f
    val context = LocalContext.current
    val indexFlow = remember(context) {
        runCatching { DataStoreAppSettings(context).fontSizeIndex }.getOrElse { flowOf(1) }
    }
    val index by indexFlow.collectAsState(initial = 1)
    return FontSizeOption.fromIndex(index).scale
}

@Composable
fun ConnectOnionTheme(
    // User-selected theme mode. SYSTEM (default) follows the OS dark-mode setting;
    // LIGHT/DARK force the corresponding palette.
    themeMode: ThemeMode = ThemeMode.SYSTEM,
    // Off by default: keep the ConnectOnion brand colors instead of letting
    // Material You (Android 12+) recolor the app from the user's wallpaper.
    dynamicColor: Boolean = false,
    // Multiplies the system Accessibility font scale for every `.sp` in the app.
    // Defaults to the persisted setting; pass explicitly to override (tests).
    fontScale: Float = userFontScale(),
    content: @Composable () -> Unit
) {
    val darkTheme = when (themeMode) {
        ThemeMode.LIGHT -> false
        ThemeMode.DARK -> true
        ThemeMode.SYSTEM -> isSystemInDarkTheme()
    }

    val targetColorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }
        darkTheme -> DarkColorScheme
        else -> LightColorScheme
    }
    // Cross-fade every color role instead of snapping when the user toggles
    // Light/Dark/System, matching the Figma design's theme transition.
    val colorScheme = targetColorScheme.animated()

    // Composed with (not substituted for) the system font scale, so the user's
    // setting stacks on top of Accessibility rather than overriding it. Applied
    // here rather than in ChatScreen so every screen honours the setting.
    val baseDensity = LocalDensity.current
    val scaledDensity = remember(baseDensity, fontScale) {
        Density(density = baseDensity.density, fontScale = baseDensity.fontScale * fontScale)
    }

    val view = LocalView.current
    if (!view.isInEditMode) {
        SideEffect {
            val window = (view.context as Activity).window
            // Edge-to-edge: both bars are transparent, so what sits behind them is
            // this theme's background/surface, not `primary` as before. "Light bars"
            // means light *background* -> dark icons, so the flags are !darkTheme.
            // Re-applied here rather than left to enableEdgeToEdge(), which keys off
            // the system uiMode and would ignore an in-app LIGHT/DARK override.
            val controller = WindowCompat.getInsetsController(window, view)
            controller.isAppearanceLightStatusBars = !darkTheme
            controller.isAppearanceLightNavigationBars = !darkTheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = AppTypography,
        shapes = AppShapes,
        content = {
            // The XML theme now has a -night variant, but it follows the
            // *system* dark setting while this palette follows the in-app
            // ThemeMode, so the two still diverge (system light + in-app DARK).
            // This Surface is what keeps screens that paint no background of
            // their own (LoadingScreen, RecoveryScreen) on the selected palette
            // rather than on the window background.
            Surface(
                modifier = Modifier.fillMaxSize(),
                color = MaterialTheme.colorScheme.background
            ) {
                CompositionLocalProvider(
                    LocalSpacing provides SpacingTokens(),
                    // Without this the status roles always resolved to their
                    // defaults, leaving light and dark identically toned.
                    LocalStatusColors provides if (darkTheme) DarkStatusColors else LightStatusColors,
                    LocalDensity provides scaledDensity
                ) {
                    content()
                }
            }
        }
    )
}
